### ISSUE TITLE
Replace mabe enums with native ones

### ISSUE THREAD

**Issue by FelixJacobi** [littleredbutton/bigbluebutton-api-php#163]
Must be done 6.0 due to being a BC break in theory.

**Comment by SamuelWei** [comment]
@FelixJacobi With the changes merged in 38f655412158410c9257aae504f4a87b373cb05e, should we release the changes since 5.1 as 5.2? I have create a draft release for it; or would this be a BC as we removed the enum library?
I guess the tought behind this issue was, that we cannot switch to native enums without bumping to PHP 8.1, which would be a BC.

**Comment by FelixJacobi** [comment]
In practice, I think no one should have used the mabe features, so we can stay at 5.x for now.
